# Generated by Django 5.2.3 on 2025-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventtype_event_duration_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='color',
            field=models.CharField(default='#3788d8', help_text='Введите цвет в формате HEX, например, #ff0000', max_length=7, verbose_name='Цвет'),
        ),
    ]
