# Generated by Django 5.2.3 on 2025-06-27 11:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='color',
            field=colorfield.fields.ColorField(default='#3788d8', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
    ]
